# Generated by Django 3.1.6 on 2022-06-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronosys', '0002_auto_20220630_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chrono_model1_v2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(blank=True)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_email', models.TextField(blank=True)),
                ('customer_contact', models.TextField(blank=True)),
            ],
        ),
    ]
