# Generated by Django 4.0.3 on 2022-07-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronosys', '0003_chrono_model1_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chrono_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_lastname', models.CharField(blank=True, max_length=100)),
                ('customer_firstname', models.CharField(blank=True, max_length=100)),
                ('customer_middleint', models.CharField(blank=True, max_length=50)),
                ('customer_address', models.CharField(blank=True, max_length=120)),
                ('customer_email', models.CharField(blank=True, max_length=100)),
                ('customer_contact', models.CharField(blank=True, max_length=100)),
                ('customer_product', models.CharField(blank=True, max_length=100)),
                ('customer_color', models.CharField(blank=True, max_length=100)),
                ('customer_quantity', models.CharField(blank=True, max_length=100)),
                ('customer_price', models.CharField(blank=True, max_length=100)),
                ('customer_tprice', models.CharField(blank=True, max_length=100)),
                ('customer_paymethod', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chrono_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_topic', models.CharField(blank=True, max_length=100)),
                ('customer_message', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Chrono_model1_v2',
        ),
        migrations.DeleteModel(
            name='ChronoBreak_form',
        ),
    ]
